services:
  db:
    image: postgres:latest
    container_name: tanstarter-database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SERVER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SERVER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SERVER_POSTGRES_DB:-tanstarter-database}
    ports:
      - "5432:5432"
    volumes:
      - tanstarter-database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tanstarter-network

volumes:
  tanstarter-database-data:

networks:
  tanstarter-network:
    driver: bridge
